Added internal dns names too

diff --git a/aws-dns b/aws-dns
--- a/aws-dns
+++ b/aws-dns
@@ -62,7 +62,38 @@ cat > ${TMPFILE} << EOF
 EOF
 
 echo "Creating dns record for $hostname that points to ip $hostname_ip"
+# Update the Hosted Zone record
+aws route53 change-resource-record-sets --hosted-zone-id $zoneid --change-batch file://"$TMPFILE"
+if [ $? -ne 0 ];
+then
+    echo "Failed to create dns record at Amazon"
+    # Clean up
+    rm $TMPFILE
+    exit 1
+fi
 
+cat > ${TMPFILE} << EOF
+{
+  "Comment":"$COMMENT",
+  "Changes":[
+    {
+      "Action":"UPSERT",
+      "ResourceRecordSet":{
+        "ResourceRecords":[
+          {
+            "Value":"10.50.41.200"
+          }
+        ],
+        "Name":"internal-$hostname",
+        "Type":"$TYPE",
+        "TTL":$TTL
+      }
+    }
+  ]
+}
+EOF
+
+echo "Creating internal dns record for $hostname that points to ip 10.50.41.200"
 # Update the Hosted Zone record
 aws route53 change-resource-record-sets --hosted-zone-id $zoneid --change-batch file://"$TMPFILE"
 if [ $? -ne 0 ];
